### ISSUE TITLE
Angular material compatibility

### ISSUE THREAD

**Issue by messteno** [d-oliveros/ngSticky#130]
Current version is not compatible with angular material, because of it's overlay layout strategy for selects, autocomplete, datepicker, etc. When they want show overlay, they changed body style, making it's position fixed, and 'top' style to negative value of current scrollY position. On finish they recover all settings back.
So this behavior breaks stickyLine variable value and sticky element won't unstick.

Codepen example:

https://codepen.io/mesteno/pen/qZpNEe

Reproduce bug:
1. scroll to second list
2. open datepicker
3. close datepicker
4. scroll top

Possible dirty fix:
Fix scrollbarYPos to ignore body negative top:

```javascript
function scrollbarYPos() {
      var position;
      if (typeof scrollbar.scrollTop !== 'undefined') {
          position = scrollbar.scrollTop;
      } else if (typeof scrollbar.pageYOffset !== 'undefined') {
          position = scrollbar.pageYOffset;
      } else {
          position = document.documentElement.scrollTop;
      }
      var bodyTop = $body.css('top').replace('px', '');
      if (bodyTop < 0) {
          position -= bodyTop;
      }

      return position;
}
```

**Comment by dmalanij** [comment]
@d-oliveros, any plan to include this? You can check on @dlorenzo-plx implementation and maybe get it through a pull request. We'd like to have support for material with the offiicial bower package you created.
Cheers

**Comment by simonered** [comment]
+1

**Comment by mAmged** [comment]
+1

**Comment by dlorenzo-plx** [comment]
With this new release, sticky elements disappear while material popup is open and reapper after it has been closed (tested with a material select control).

The issue with elements not ever unsticking seems to be fixed though. All in all, incompatibility between Angular Material and ngSticky still persists.

**Comment by kianlavi** [comment]
I would +1 this again. This would be rad to use with my angular-material project. Wouldn't want to have to roll it myself since your solution seems really well thought-out.
