### ISSUE TITLE
Fixed position within a parent element

### ISSUE THREAD

**Issue by DomAndDominik** [d-oliveros/ngSticky#131]
I was playing around to make this working but I was unable to get it done. 
**The goal** is to have a fixed position within certain parent element and when at the bottom of parent element view make absolute position to bottom. 

You guys had to seen it in [action](http://www.apple.com/shop/buy-iphone/iphone6s) many times.

Any thoughts appreciated.

**Comment by Ron-ThreeMysticApes** [comment]
check out my update
https://github.com/d-oliveros/ngSticky/pull/133

**Comment by LukasChen** [comment]
use ```confine="true"```

**Comment by edbentinck** [comment]
@LukasChen `confine="true"` doesn't solve the issue mentioned. `confine` sets `position: relative;` on the parent, but that has no effect in this scenario because the child element is has a fixed position.

The PR submitted by @Ron-ThreeMysticApes does the job.

**Comment by DomAndDominik** [comment]
@edbentinck  a child element has fixed position until it hits the bottom of a parent wrapper. Works well.

**Comment by edbentinck** [comment]
@DomAndDominik I assume we are referring to different use cases then because I tried it and it had no effect. Good thing it worked for you 👍
