### ISSUE TITLE
$compile error when I include this in my app

### ISSUE THREAD

**Issue by sroberson** [d-oliveros/ngSticky#25]
I have a very simple page into which I'm sprinkling AngularJS 1.3.x.  I wanted to use your sticky directive, but when I include it in my page, I'm getting a $compile error.

```
var app = angular.module('susquhannaApp', ['ui.bootstrap','sticky']);

<nav sticky role="navigation" id="main-nav" ng-controller="MainNavController">
    <ul>
        <li><a href="">Home</a></li>
        <li><a href="">About</a></li>
        <li><a href="">Products</a></li>
        <li><a href="">Support</a></li>
    </ul>
</nav>
```

Error: error:multidir
Multiple Directive Resource Contention

**Comment by d-oliveros** [comment]
Sweet! Let me know if you still have issues with the library. I updated it to v1.7.6 just now :)
