### ISSUE TITLE
Sticky when not "window" is the one that scrolls

### ISSUE THREAD

**Issue by xeor** [d-oliveros/ngSticky#39]
I am using Angular Material, and a part of that layout makes my content element the one that scrolls, not the "window" itself. My header, and left/right menues all stays in place.
So, `angular.element(window).on('scroll', function() { console.log('scrolled')(); })` gives no output when scrolling, but `angular.element(document.getElementById("myStickyID")).on('scroll', function() { console.log('scrolled')(); })` does.

Is it possible to add more dynamic of what to watch when scrolling, or will that possible break other things?

**Comment by blindenvy** [comment]
+1 for this functionality.

**Comment by EnigmaticCode** [comment]
I'm currently working for a client that desires this behavior and is open to forking the project.  Expect it in the coming weeks.

**Comment by EnigmaticCode** [comment]
@xeor @blindenvy 

This functionality should be in place as of #86.  Let me know if you have any problems.

**Comment by xeor** [comment]
@EnigmaticCode thats great! I am not currently working on the same project anymore, but I will def keep in mind that ngSticky supports this now. It will be useful in a lot of upcoming projects :)
