### ISSUE TITLE
Lose 'sticky' after page reload

### ISSUE THREAD

**Issue by celsomtrindade** [d-oliveros/ngSticky#55]
The code works fine, but the problem is when i refresh the page.
For example:

I load the page, scroll down, refresh the page and then scrolls back to the top. The sticky element will lose it's 'sticky', and will stay always at the top until i change the route or reload the page at the very top.

**Comment by lelandcope** [comment]
Im also having the same issue. Anyone have a fix for it?

**Comment by Fourwinged** [comment]
Looks like it should be like this :

    return element.getBoundingClientRect().top + document.documentElement.scrollTop;

Instead of 

    return element.getBoundingClientRect().top;
