### ISSUE TITLE
What about create a new bower version with the new fixes?

### ISSUE THREAD

**Issue by angelolucas** [d-oliveros/ngSticky#61]
Hello @d-oliveros. 

Thank you for your project. It's helping me a lot. 

I saw the latest fixes done by @kamilkp. It helps me in my project, the problem is that a new tag (bower version) was not released. Can you do that, please?

Thank you.

**Comment by kamilkp** [comment]
Also update npm package please.

**Comment by raulromanp** [comment]
+1

**Comment by westonganger** [comment]
+1 please continue using the versioning more often

**Comment by mackelito** [comment]
Any updates on this?
