### ISSUE TITLE
ngSticky does not work inside of ion-nav-view

### ISSUE THREAD

**Issue by leongaban** [d-oliveros/ngSticky#74]
http://stackoverflow.com/questions/32237459/ngsticky-not-working-when-the-sticky-a-directive-is-inside-of-a-template

I'm using the Ionic framework, which uses `ion-nav-view` instead of `ui-view`.

In my demo link here you can see that the sticky doesn't work: http://leongaban.com/sticky/#/ I wrote this page locally without the template inserted into the `ion-nav-view` and the sticky worked as expected.

Is there a work around to get it working again from inside an inserted template?

**Comment by leongaban** [comment]
Figure out the issue, the parent div has the style `translate3D` which breaks the `sticky` directive from working. That parent div is part of the ionic framework, so I'll have to programmatically remove it / restyle after load.

 `transform: translate3d(0%, 0px, 0px)` style on the parent div.

**Comment by w3development-kn** [comment]
When commenting this out, the view stops scrolling.
