### ISSUE TITLE
Some extraneous inline styles mess up layout : ( height = 0px bug )

### ISSUE THREAD

**Issue by mattmutt** [d-oliveros/ngSticky#90]
I am enjoying this ngSticky with the newly introduced  `DIV` based scrolling support ( _not on the browser `window` object_ ). Basic support that was added recently *almost* works. Let me describe the symptoms that I am seeing.

As mentioned, I set up the `sticky-scroll` element directive and inside have a long list of content. The title near the top is going to be sticky. So I write 2 nested `DIV` tags place the `sticky`  ( trust me, I could write 1, but 2 seemed to overcome the bug by hardcoding (which I am doing as a last resort, not by clear choice ) ).

I have noticed that upon going from pinned to unpinned states there is some inlined styles applied. That's fine if absolutely necessary, but it messes up my layout

Here's the dump. Looks innocuous. but no. far from it. the dreaded height = 0 destabilizes my content. and even though the position is fixed ( I copied it when it was in a sticky position, the height 0 remains for eternity ). This is bad, because my CSS definitions are devastated by the cascade of inlines. Height 0 destroys static layouts. I also do *not* hardcode widths and heights in my classes because the content is just that - simple titles and such. 
 
```
element.style {
    height: 0px;
    z-index: 10;
    width: 270px;
    top: 65px;
    position: fixed;
    left: auto;
    margin-top: 0px;
}
```
 
Can someone else chime in if this height:0 is a bug or by design choice. I can overcome most of these artifacts by caving in and hardcoding pixel widths and heights in the markup, thus losing any power of the stylesheet. shouldn't have to

**Comment by mattmutt** [comment]
I've been making drastic overhauls to directive code. Would anyone like to validate my work or merge the PR?

https://github.com/d-oliveros/ngSticky/pull/91

it helps  resolve the issue I posted above

**Comment by EnigmaticCode** [comment]
Just an FYI you can pass $controller as the 4th parameter to link and assign things that way.  I generally prefer to avoid assigning things to $scope.  It's not a big deal though and seems to be functioning, try emailing the author for approval.

@d-oliveros

**Comment by EnigmaticCode** [comment]
Oh, you might want to update the minified file and version.

**Comment by mattmutt** [comment]
oh .. I forgot to minify. So used to the build tools doing that.

As for your point about the $controller, I will make an example that shows the nesting of directives so you can see it in action.  Directive A ( sticky ) will wrap some content box ( Directive B ).  Directive B knows about being inside of a sticky. You may have the opinion that child should not know about it parent. If you have a strong stance, I would have to put logic into the sticky's directive. Either way the end result is about the same...

Let me work on a sample later...

**Comment by mattmutt** [comment]
Ok I added minification and a new demo to showcase stickies with asynchronously loaded / resized content. I'll expand upon this example in `dynamic-sticky-content` folder as I try to illustrate even more obscure edge cases, that maybe others have. For now you can try the demo, click the "change city" and see the sticky reload. Maybe not so impressive, but its reusing the sticky component without refreshing the whole page. Do you have other edge cases to consider?

I emailed author last week, no response.
