### ISSUE TITLE
How to recompute the stickyBottomLine

### ISSUE THREAD

**Issue by ahmehri** [d-oliveros/ngSticky#92]
My scenario is confine a sticky menu to a parent that gets changed (its height) many times. So when initializing the sticky menu, it will compute a wrong stickyBottomLine. How to recompute this stickyBottomLine each time the parent height is changed?

**Comment by jordanchapian** [comment]
To do this, I added a watch on the parent's top offset and height. Then to update, you'll basically follow procedure in onChange.

**Comment by madhaze** [comment]
@jordanchapian can you give more information on how you did this.  Did you do this in your own app and trigger the onChange in ngSticky?  Would love to see your solution.
