### ISSUE TITLE
Jerky animation & multiple placeholders created

### ISSUE THREAD

**Issue by FiniteLooper** [d-oliveros/ngSticky#97]
I upgraded this directive in my project from version 1.7.10 to the current 1.8.3 and experienced some issues that are preventing me from keeping the updated version.  I decided to make a simple demo to show the issues I was seeing, but the basic demo turned out to have a bunch of issues of it's own.

basically I am using this

``` javascript
 $scope.headerIsSticky=true;
```

``` html
<header sticky
        sticky-class="is-sticky"
        stick-limit="true"
        use-placeholder="true"
        disabled-sticky="!headerIsSticky"
        media-query="(min-width: 992px) and (min-height: 700px)">
    <h1>Sticky Header</h1>
    <label>
      <input type="checkbox" ng-model="headerIsSticky" /> Sticky?
    </label>
</header>
```

:beetle:  When the window small & is below the triggers for the media query multiple placeholder elements are created. My content gets pushed down the page further and further.  The header element rapidly switches between being sticky and not being sticky.
:beetle: When the element is scrolled down and stick, and then I disable the stickiness, the placeholder element still remains and take up space when it should not
# Demos

(When viewing the demos, be sure to open it in a new window it doesn't play well with the scrollable frame on the plnkr website.)

**Code using v1.8.3:** http://plnkr.co/edit/2MUAL8sw0IX3QnVbLvEg?p=preview

![animation 0](https://cloud.githubusercontent.com/assets/463685/10641971/a3775164-77e9-11e5-802e-9db43f4efcc0.gif)

The above code works perfectly in version 1.7.11, so these seem like regression bugs.
**Code using v1.7.11:** http://plnkr.co/edit/XR30tyL1Y0RsLu5MMYHj?p=preview

![1 7 11](https://cloud.githubusercontent.com/assets/463685/10641885/2dac9c3c-77e9-11e5-915b-9a9b26a41050.gif)

**Comment by forwardt** [comment]
I am experiencing the same issue here.

**Comment by pbtura** [comment]
Have you tried upgrading to 1.84? It looks like the latest version has some fixes for the placeholder creation.

**Comment by chrismbarr** [comment]
Nope, still has some issues.  Here's the same test with **v1.8.5** now: http://plnkr.co/edit/ADRCObbB0mzgK2Pg0Okw?p=preview

To recreate issues: Open that link and click the blue "launch preview in a separate window" icon in the upper left of the preview (this directive doesn't play well when in a frame)

**Issue 1** - placeholder not removed
To recreate:

1. use the link 7 instructions above.
2. Ensure that the "sticky?" box is checked
3. Scroll down a bit
4. uncheck the box
5. scroll back up to the top
6. :beetle: the placeholder is still there taking up space.
7. :beetle: Toggling the checkbox does not add/remove the placeholder.

**Issue 2** - jerky craziness when using the responsive features
To recreate:

1. use the link 7 instructions above.
2. Ensure that the "sticky?" box is checked
3. resize the window to be more narrow, less than 992 pixels wide
4. :beetle: scroll down - the sticky element jumps in and out of the view like crazy
5. :beetle: scroll back up, the placeholder remains taking up space.
7. :beetle: Toggling the checkbox does not add/remove the placeholder.

**Comment by mackelito** [comment]
+1 on this issue

**Comment by chrismbarr** [comment]
**UPDATE:** I tried this again with version 1.8.6 (maybe 1.8.7 though?  The `package.json` file has a different version number than the version in the JS file... hard to tell what version is out right now)

It appears that **Issue 2** from my last comment 5 months ago has been fixed, however **Issue 1** still remains.

Here is an updated demo link: http://plnkr.co/edit/BEK8JIYErmv7vhr5U1HU

**Remaining Issue: placeholder not removed**
To recreate:
 1. Open the link above and click the blue "launch preview in a separate window" icon in the upper left of the preview (this directive doesn't play well when in a frame)
 2. use the link & instructions above.
 3. Ensure that the "sticky?" box is checked
 4. Scroll down a bit
 5. uncheck the box
 6. scroll back up to the top
 7. :beetle: the placeholder is still there taking up space.
 8. :beetle: Toggling the checkbox does not add/remove the placeholder.

**please please please** find a fix for this.  Basically we are all required to use a much older version _(with other undesirable bugs)_ until this is fixed.

**Comment by chrismbarr** [comment]
The issue remains with latest release (1.8.10)
Demo: http://plnkr.co/edit/PZJknd1UEptvtp8uEDKZ?p=preview
